version: '3'
services:

  nginx:
    image: nginx:1.15.1
    container_name: nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"

  db:
    container_name: "db"
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  mysql:
    image:  mysql/mysql-server:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  app:
    container_name: thorntail-example-thorntail
    build:
      context: .
      dockerfile: Dockerfile
    image: thorntail-example-thorntail:latest
    environment:
       - SWARM_DATASOURCES_DATA_DASH_SOURCES_SOMEDS_CONNECTION_DASH_URL=jdbc:mysql://db:3306/test?useSSL=false
    links:
      - db
      - keycloak
    ports:
      - "8443:8443"
      
    depends_on:
      - db
      - keycloak

  keycloak:
    build: ./DockerKeycloak
    restart: on-failure
    environment:
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - JDBC_PARAMS=useSSL=false
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json"
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/realm-export.json
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  db-data: {}
  mysql_data:
    driver: local
